function [B]= SOLVER(N,A,B,IP)
%	REAL A(N,N),B(N),T
%	INTEGER IP(N)
%	SOLUTION OF LINEAR SYSTEM, A*X=B.
%	N=ORDER OF MATRIX.
%	B=RIGHT HAND SIDE VECTOR.
%	IP=PIVOT VEVTOR OBTAINED FROM SUBROUTINE DECOMP.
%	B=SOLUTION VECTOR X.
%
NM1=N-1;
KP1=K+1;
M=IP(K);
T=B(M);
KM1=N-KB;
K=KM1+1;
T=-B(K);