function [IP,A]= DECOMP(N,A)
%	REAL A(NDIM,NDIM),T
%	INTEGER IP(NDIM)
%	MATRIX TRIANGULARIZATION BY GAUSSIAN ELIMINATION.
%	N = ORDER OF MATRIX. NDIM = DECLARED DIMSISION OF ARRAY A.
%	A = MATRIX TO BE TRIANGULARIZED
%	IP(K) , K .LT. N = INDEX OF K-TH PIVOT ROW.
%
KP1=K+1;
M=K;
M=I;
T=A(M,K);
T=A(M,J);